spring.application.name=Posting
spring.datasource.username=postgres
spring.datasource.password=SmiSup704
spring.datasource.url=jdbc:postgresql://localhost:5432/PostingDB
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
jwt.secret.access=bkZYu9rQJ6JZq/Fxu0InDM7IOXl8Q2N6ExU3/v6aMoo=
jwt.secret.refresh=Bvsr5bsqgV3d43gfVarQJH6j7DvfstWytf4lf9mOaHI=